In [1]:
# np.where
import numpy as np
# 1d
arr = np.array([10,3,4,80,90,6,7])
print(arr)
 
# np.where
arr_w = np.where(arr>20,"True","False") # (condition)?"True":"False"
print(arr_w)
 

[10  3  4 80 90  6  7]
['False' 'False' 'False' 'True' 'True' 'False' 'False']


In [4]:
arr1 = np.array([10,3,4,80,90,6,7])
print(arr1)

#np.where
result1 = arr1[np.where(arr1>20)]# in index
print(result1)


[10  3  4 80 90  6  7]
[80 90]


In [5]:
import numpy as np
arr = np.array([11,20,22,40,45,60])
print(arr)

#even index
even_index = np.where(arr % 2 == 0)
print(even_index)

#value
even_index = arr[np.where(arr % 2 == 0)]
print(even_index)




[11 20 22 40 45 60]
(array([1, 2, 3, 5], dtype=int64),)
[20 22 40 60]


In [6]:
#np.where use as replace
arr = np.array([11,20,22,40,45,60])
print(arr)

#np.where
result = np.where(arr>20,100,0)#condition? "True":"False"(Same like ternary operator)
print(result)


[11 20 22 40 45 60]
[  0   0 100 100 100 100]


In [8]:
#np.where for 2d
import numpy as np
arr = np.array([
    [10,20,25],
    [45,50,55],
    [60,20,70]
])

print(arr)

#np.where
result = np.where(arr>40)
print(result) #index of row,index of cols
#1 0 ->45
#1 1 ->50
#1 2 ->55
#2 0 ->60
#2 2 ->70

[[10 20 25]
 [45 50 55]
 [60 20 70]]
(array([1, 1, 1, 2, 2], dtype=int64), array([0, 1, 2, 0, 2], dtype=int64))


In [10]:
import numpy as np
arr = np.array([
    [10,20,25],
    [45,50,55],
    [60,20,70]
])

print(arr)

#np.where
rows,cols = np.where(arr>40)
print(rows)
print(cols)

#final value
print(arr[rows,cols])

[[10 20 25]
 [45 50 55]
 [60 20 70]]
[1 1 1 2 2]
[0 1 2 0 2]
[45 50 55 60 70]


In [11]:
import numpy as np
arr = np.array([
    [10,20,25],
    [45,50,55],
    [60,20,70]
])
print(arr)
 
# np.where
result = np.where(arr>40)
print(type(result))
print(result[0]) # rows
print(result[1]) # cols
 
# final value
print(arr[result[0],result[1]])
 
# np.where | alternative
# rows,cols = np.where(arr > 40)
# print(rows) # rows
# print(cols) # cols
 
# final value
# print(arr[rows,cols])
 

[[10 20 25]
 [45 50 55]
 [60 20 70]]
<class 'tuple'>
[1 1 1 2 2]
[0 1 2 0 2]
[45 50 55 60 70]


In [12]:
import numpy as np
arr = np.array([
    [10,20,25],
    [45,50,55],
    [60,20,70]
])
print(arr)
 
# np.where
result = np.where(arr>=36,"Pass","Fail")
print(result)

[[10 20 25]
 [45 50 55]
 [60 20 70]]
[['Fail' 'Fail' 'Fail']
 ['Pass' 'Pass' 'Pass']
 ['Pass' 'Fail' 'Pass']]


In [14]:
Data = np.array([208,300,500,460,660])
print(Data)

#np.where
Data_1 = Data[np.where(Data>300)]
print(Data_1)


[208 300 500 460 660]
[500 460 660]


In [15]:
import numpy as np
arr = np.array([
    [100,200,253],
    [457,500,550],
    [600,205,703]
])
print(arr)
 
# np.where
result = np.where(arr % 2 == 0,"Even","odd")
print(result)

[[100 200 253]
 [457 500 550]
 [600 205 703]]
[['Even' 'Even' 'odd']
 ['odd' 'Even' 'Even']
 ['Even' 'odd' 'odd']]


In [19]:
#np.concatenate
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])

#np.concatenate
result = np.concatenate((arr1,arr2))
print(result)

result1 = arr1 + arr2
print(result1)

[10 20 30 40 50 60]
[50 70 90]


In [20]:
#2d array
import numpy as np
arr1 = np.array([
    [10,20],
    [30,40]
])
arr2 = np.array([
    [50,60],
    [7,80]
])

result = np.concatenate((arr1,arr2)) # (0)row -wise
print(result)

result = np.concatenate((arr1,arr2),axis=1) #(1)col - wise
print(result)


[[10 20]
 [30 40]
 [50 60]
 [ 7 80]]
[[10 20 50 60]
 [30 40  7 80]]
